ALTER TABLE ips ADD COLUMN IF NOT EXISTS reputation_score INT NOT NULL DEFAULT 70;
ALTER TABLE ips ADD COLUMN IF NOT EXISTS volume_decision TEXT NOT NULL DEFAULT 'hold';
ALTER TABLE ips ADD COLUMN IF NOT EXISTS listed_on TEXT NOT NULL DEFAULT '';
ALTER TABLE ips ADD COLUMN IF NOT EXISTS last_probe_at TIMESTAMPTZ;
